---
title: "Estimating the value of Pi with a Monte Carlo approach"
author: "Jacob L. Fine"
date: "April 20th, 2024"
output: html_document
---

Here, we will implement a classic Monte Carlo method used for estimating the value of Pi.
To achieve this, we will generate random points in the first quadrant of a two-dimensional
Cartesian coordinate system such that they are in the positive region defined by the
equation of a unit circle x^2 + y^2 = 1. We will first provide a mathematical basis for 
why the simulation provides an unbiased and consistent estimate of pi.

The probability that a randomly generated point $(x,y)$ falls within the portion of the unit circle in the first quadrant is exactly $p=\pi/4$, which is the expected value of the proportion of points in that region. We therefore have

$$E(\hat{p}) = \pi/4$$

which makes our estimator unbiased since

$$E(\hat{p})-p= \pi/4 -\pi/4=0$$

By the Weak Law of Large Numbers (WLLN), the estimator $\hat{p}$ of the true proportion $p$ will converge in probability to the true proportion, such that

$$\hat{p} \rightarrow^p p=\pi/4$$
which makes our estimator consistent.


# sets the random seed
set.seed(2000127)

# defines the function to estimate pi
pi_estimate <- function(n_points) {
# the original number of points inside the circle region
  points_inside_circle <- 0
# generates all the points
  for (i in 1:n_points) {
  
# generates a pair of values x and y from a standard uniform distribution
    x <- runif(1, 0, 1)
    y <- runif(1, 0, 1)
# computes the distance from the origin
    radius_squared <- x^2 + y^2
# if the distance is within the region bounded by the circle, count that as a point inside the circle
    if (radius_squared <= 1) {
      points_inside_circle <- points_inside_circle + 1
    }
  }
# we are estimating pi/4 (points_inside_circle / n_points), so multiply by 4 to obtain pi
  return(4 * points_inside_circle / n_points)
}

# set the number of iterations (points) to generate
n_points <- 100000

# calls the function to estimate pi
pi_estimate <- pi_estimate(n_points)
cat("Estimated value of Pi using", n_points, "points:", pi_estimate, "\n")

# stores the true value of pi
true_pi <- pi

# finds the difference between the estimated value of pi and the true value
difference <- abs(pi_estimate - true_pi)
cat("Number of simulations:", n_points, "\n")
cat("Estimated value of pi:", pi_estimate, "\n")
cat("Difference between estimated pi and true pi:", difference, "\n")


